### ISSUE TITLE
Meat Items Missing from Category

### ISSUE THREAD

**Issue by jwaisner** [N6REJ/AdiBags_Bears_Cooking#21]
The following items I have found do not properly go under the "meat" category:

Basilisk Eggs

![image](https://user-images.githubusercontent.com/12568201/205544679-6ef26a97-2c0e-4376-8aa1-917bf37d938e.png)

Hornswog Hunk

![image](https://user-images.githubusercontent.com/12568201/205544726-4f991fbb-8d67-4e94-89ce-fff2b0421894.png)

**Comment by N6REJ** [comment]
Should be fixed in Cooking 2022.12.05
